---
- name: Install Docker on EC2 instance
  hosts: all
  become: yes

  tasks:
  - name: Display OS Distribution
    debug:
      msg:
        - "Distribution: {{ ansible_distribution }}"
        - "Major Version: {{ ansible_distribution_major_version }}"
  
  - name: Update YUM repository cache
    yum:
      update_cache: yes
    when: ansible_os_family == 'RedHat'

  - name: Install Docker using yum
    yum:
      name: docker
      state: present
    when: ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2023'

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes
